apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-base-app-auth
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: auth
        image: simonbaeckap/chatbase-authapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000